server:
  port: 8080
spring:
  application:
#    应用名称，是可选的
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: qwxy74152077
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
#    这里可以设置全局的mybatis-plus配置，比如数据库表有t_user这种前缀,就可以使用
    #global-config:db-config:   table-prefix: t_
    db-config:
#      主键生成策略（雪花算法），随机生成id
      id-type: ASSIGN_ID
reggie:
  path: D:\\reggie\\photo\